2025-08-23 17:35:22,141 INFO: BeRAM startup [in D:\BeRAM-Website\BeRam-Website\beram\errors.py:44]
2025-08-23 17:37:29,899 INFO: BeRAM startup [in D:\BeRAM-Website\BeRam-Website\beram\errors.py:44]
2025-08-23 17:52:07,039 INFO: BeRAM startup [in D:\BeRAM-Website\BeRam-Website\beram\errors.py:44]
2025-08-23 17:52:22,116 ERROR: Exception on /mission-statement [GET] [in C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\BeRAM-Website\BeRam-Website\beram\main\routes.py", line 133, in mission_statement
    return render_template('mission_statement.html', title='Our Mission')
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\BeRAM-Website\BeRam-Website\beram\templates\mission_statement.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\BeRAM-Website\BeRam-Website\beram\templates\base.html", line 48, in top-level template code
    {% block content %}
  File "D:\BeRAM-Website\BeRam-Website\beram\templates\mission_statement.html", line 109, in block 'content'
    <li><a href="{{ url_for('main.dcis') }}">DCIS (Drone Cloud Intelligence System)</a></li>
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.dcis'. Did you mean 'main.index' instead?
2025-08-23 17:52:22,186 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in D:\BeRAM-Website\BeRam-Website\beram\errors.py:15]
2025-08-23 18:00:11,659 INFO: BeRAM startup [in D:\BeRAM-Website\BeRam-Website\beram\errors.py:44]
2025-08-23 18:00:12,542 INFO: BeRAM startup [in D:\BeRAM-Website\BeRam-Website\beram\errors.py:44]
2025-08-23 18:11:59,366 INFO: BeRAM startup [in D:\BeRAM-Website\BeRam-Website\beram\errors.py:44]
2025-08-23 18:12:47,550 INFO: BeRAM startup [in D:\BeRAM-Website\BeRam-Website\beram\errors.py:44]
2025-08-23 18:17:57,085 INFO: BeRAM startup [in D:\BeRAM-Website\BeRam-Website\beram\errors.py:44]
2025-08-23 18:24:42,773 INFO: BeRAM startup [in D:\BeRAM-Website\BeRam-Website\beram\errors.py:44]
2025-08-24 13:08:43,232 INFO: BeRAM startup [in D:\BeRAM-Website\beram\errors.py:44]
2025-08-24 13:09:39,817 ERROR: Exception on /mission-statement [GET] [in C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\BeRAM-Website\beram\main\routes.py", line 133, in mission_statement
    return render_template('mission_statement.html', title='Our Mission')
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\BeRAM-Website\beram\templates\mission_statement.html", line 320, in template
    <p class="small text-muted mt-3 mb-0">Last updated: {{ (now or '')|string[:10] or '2025-08-01' }}</p>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '['
2025-08-24 13:09:39,985 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in D:\BeRAM-Website\beram\errors.py:15]
2025-08-24 13:09:42,382 ERROR: Exception on /mission-statement [GET] [in C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\BeRAM-Website\beram\main\routes.py", line 133, in mission_statement
    return render_template('mission_statement.html', title='Our Mission')
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\BeRAM-Website\beram\templates\mission_statement.html", line 320, in template
    <p class="small text-muted mt-3 mb-0">Last updated: {{ (now or '')|string[:10] or '2025-08-01' }}</p>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '['
2025-08-24 13:09:42,391 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in D:\BeRAM-Website\beram\errors.py:15]
